development:
  host: localhost
  username: root
  password:
  database: watsonint
  adapter: mysql2
  reconnect: true
  
staging:
  host: 23.22.61.75
  username: root
  password: V@nil!a1
  database: watsonint
  adapter: mysql2
  reconnect: true
  
production:
  host: localhost
  username: root
  password:
  database: watsonint
  adapter: mysql2
  reconnect: true